import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "../globals.css";
import { Providers } from "@/components/modules/providers";
import Navbar from "@/components/modules/navbar";

const vazir = Vazirmatn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vazir.className} h-[200vh] bg-[#FAFAFA]`}>
        <Providers>
          <Navbar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
